n_clusters: 4
k_values: [4]  # Lista con uno o más valores de k
imputation_strategy: mean
plot_titles:
  dbscan: "Resultados de Clustering con DBSCAN"
  hierarchical: "Resultados de Clustering Jerárquico"

feature_names:
  - review_time
  - review_aroma
  - review_appearance
  - review_palate
  - review_taste
  - beer_abv
  - beer_beerid
  - otras_columnas_dummies_si_existen
